name: Arrow windows-arm64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          choco install ninja

      - name: Build Appache Arrow windows-arm64
        run: |
           .github\scripts\build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apache-arrow-windows-arm64
          path: .\build\apache-arrow-windows-arm64.zip
          retention-days: 30